/**
 * Progressive-web-app pieces: the manifest, the <head> tags every page needs, and a service
 * worker that precaches the whole book so it reads offline once installed or first visited.
 *
 * Every URL is relative, so the book works at a domain root or under a subpath (a GitHub Pages
 * project site, say). The cache name carries a hash of the built content, so any rebuild
 * invalidates the previous cache on the next visit.
 */

export const ICONS = [
  { src: "icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  { src: "icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
  { src: "icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
];

export const ICON_FILES = [
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-192.png",
  "icon-maskable-512.png",
  "apple-touch-icon.png",
  "favicon-32.png",
];

/** bench-sheet's paper color in each theme (--paper), used for the browser chrome. */
const PAPER_LIGHT = "#f3f5f1";
const PAPER_DARK = "#12171c";
const INK = "#1b252e";

export interface ManifestInput {
  title: string;
  subtitle: string;
  dek: string;
}

export function manifest(b: ManifestInput): string {
  return JSON.stringify(
    {
      id: "./",
      name: `${b.title}: ${b.subtitle}`,
      short_name: b.title,
      description: b.dek,
      lang: "en",
      start_url: "./index.html",
      scope: "./",
      display: "standalone",
      background_color: INK,
      theme_color: INK,
      categories: ["books", "education", "developer"],
      icons: ICONS,
    },
    null,
    2,
  );
}

export function headTags(title: string): string {
  return [
    `<link rel="manifest" href="manifest.webmanifest">`,
    `<meta name="theme-color" content="${PAPER_LIGHT}" media="(prefers-color-scheme: light)">`,
    `<meta name="theme-color" content="${PAPER_DARK}" media="(prefers-color-scheme: dark)">`,
    `<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32.png">`,
    `<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">`,
    `<meta name="apple-mobile-web-app-title" content="${title}">`,
    `<meta name="mobile-web-app-capable" content="yes">`,
  ].join("\n");
}

/** Insert the PWA head tags just before </head>. */
export function withHeadTags(html: string, title: string): string {
  const i = html.indexOf("</head>");
  if (i < 0) throw new Error("page has no </head>");
  return html.slice(0, i) + headTags(title) + "\n" + html.slice(i);
}

/** Short content hash for the cache name. */
export async function contentVersion(files: Map<string, string | Uint8Array>): Promise<string> {
  const enc = new TextEncoder();
  const parts: Uint8Array[] = [];
  for (const k of [...files.keys()].sort()) {
    const v = files.get(k) ?? "";
    parts.push(enc.encode(k), typeof v === "string" ? enc.encode(v) : v);
  }
  const total = parts.reduce((n, p) => n + p.length, 0);
  const all = new Uint8Array(total);
  let o = 0;
  for (const p of parts) {
    all.set(p, o);
    o += p.length;
  }
  const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", all));
  return [...digest.slice(0, 6)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * The service worker. Same-origin requests are served cache-first (the book is static and the
 * cache is versioned); Google Fonts are cached at runtime, stale-while-revalidate; a navigation
 * that misses both network and cache falls back to the cover.
 */
export function serviceWorker(version: string, precache: string[]): string {
  return `// celld book service worker · generated by src/pwa.ts · cache ${version}
const CACHE = "celld-book-${version}";
const FONTS = "celld-book-fonts";
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin === "https://fonts.googleapis.com" || url.origin === "https://fonts.gstatic.com") {
    e.respondWith(caches.open(FONTS).then(async (c) => {
      const hit = await c.match(req);
      const fresh = fetch(req).then((res) => {
        if (res.ok || res.type === "opaque") c.put(req, res.clone());
        return res;
      }).catch(() => hit);
      return hit ?? fresh;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res.ok) cache.put(req, res.clone());
      return res;
    } catch (err) {
      if (req.mode === "navigate") {
        const cover = await cache.match("index.html");
        if (cover) return cover;
      }
      throw err;
    }
  })());
});
`;
}

/** Page-side registration, appended to the book's script. Only where service workers are allowed. */
export const REGISTER_JS = `
(() => {
  if (!("serviceWorker" in navigator) || !window.isSecureContext) return;
  addEventListener("load", () => navigator.serviceWorker.register("sw.js").catch(() => {}));
})();
`;
